// <auto-generated />
namespace TH.lab02_02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class dbnewstudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbnewstudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202412210730549_db-new-student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
